# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 3g8mysql
  host: 127.0.0.1

development:
  <<: *default
  database: hello_world_rails_development

test:
  <<: *default
  database: hello_world_rails_test

production:
  <<: *default
  database: hello_world_rails_production
